site_name: Базы данных
site_url: https://dbasedev.ru/
site_description: Справочник по базам данных
site_author: dbasedev.ru
copyright: (C) 2023, Справочник по базам данных

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/dbasedev.ru'

theme:
    name: material
    custom_dir: overrides
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: teal
          accent: teal
          toggle:
              icon: material/toggle-switch-off-outline
              name: Тёмная тема
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: teal
          accent: teal
          toggle:
              icon: material/toggle-switch
              name: Светлая тема
    language: ru
    features:
        - navigation.tabs
        - navigation.tracking
        - navigation.instant
        - navigation.top
        - content.action.edit
    favicon: db.svg
    logo: db.svg
    icon:
        edit: material/pencil
        view: material/eye

extra:
    generator: false
    social:
        - icon: fontawesome/brands/html5
          link: 'https://hcdev.ru/'
          name: HTML and CSS docs
        - icon: fontawesome/brands/js
          link: 'https://scriptdev.ru/'
          name: Javascript
        - icon: fontawesome/brands/angular
          link: 'https://angdev.ru/'
          name: Angular docs
        - icon: fontawesome/brands/react
          link: 'https://reactdev.ru/'
          name: React docs
        - icon: fontawesome/brands/node-js
          link: 'https://nodejsdev.ru/'
          name: Node.js docs
        - icon: fontawesome/brands/python
          link: 'https://py3dev.ru/'
          name: Python 3 docs
        - icon: fontawesome/solid/code
          link: 'https://xsltdev.ru/'
          name: XSLT docs
        - icon: fontawesome/solid/database
          link: 'https://dbasedev.ru/'
          name: Базы данных

#google_analytics:
#    - UA-34215161-1
#    - auto

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.superfences

plugins:
    - search:
          separator: '[\s\-\:]+'
          lang:
              - ru
              - en
    - awesome-pages
    - section-index
    - social

extra_css:
    - '/assets/stylesheets/styles.css?3'
